name: .NET Core Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'

    - name: Restore dependencies
      run: dotnet restore learningapp/learningapp.csproj

    - name: Build
      run: dotnet build --configuration Release learningapp/learningapp.csproj

    - name: Publish
      run: dotnet publish -c Release -o ./output learningapp/learningapp.csproj

    - name: Upload artifact for deployment
      uses: actions/upload-artifact@v3
      with:
        name: published-app
        path: ./output
